apiVersion: apps/v1
kind: Deployment
metadata:
  name: association
  labels:
    app: association
spec:
  replicas: 1
  selector:
    matchLabels:
      app: association
  template:
    metadata:
      labels:
        app: association
    spec:
      containers:
        - name: association
          image: "username/association:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
