apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer
  labels:
    app: volunteer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer
  template:
    metadata:
      labels:
        app: volunteer
    spec:
      containers:
        - name: volunteer
          image: "username/volunteer:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
